////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== OSGi Agent

For using an agent within an OSGi container, Jolokia comes with
agents packaged OSGi bundles. They come in two flavours:

* The standard bundle which requires an OSGi HttpService
as specified by the OSGi group. Prominent implementations of this
service are https://wiki.ops4j.org/display/paxweb/Pax+Web[Pax Web,role=externalLink] and
https://felix.apache.org/site/apache-felix-http-service.html[Apache
Felix HttpService,role=externalLink]. This bundle fits best the OSGi philosophy of
modularity and is hence the recommended bundle.
* A all-in-one bundle with no external dependencies except to the
`org.osgi.service.log.LogService` OSGi bundle. It includes the
Apache Felix HttpService which in turn includes a Jetty server. T
embedded Jetty server and is suitable for situations where ease of
deployment is more important than modularity.

Note, that some OSGi container (like Eclipse Virgo) comes with a so
called _Web extender_ which allows for deployment of standard
Webarchives (war). For such container, there is a choice between the
OSGi bundle and the WAR agent, where the later is probably easier to
deploy since there is already an HTTP server running in such
containers, which not necessarily export an OSGi HTTP service
required by the standard bundle.

More details about the OSGi agents can be found in the
link:../reference/html/agents.html#agents-osgi[Jolokia reference manual].
