= New Jolokia JavaScript library using ES modules

Changes comparing to existing jolokia.js:

* no dependency on https://jquery.com/[JQuery], https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API[Fetch API] is used for requests. Switching away from `xhr`, we're dropping _synchronous AJAX_ (`xhr` has an option to perform requests in synchronous manner, but it blocks the event loop and is deprecated in modern browsers for long time already).
** `credentials` and `headers` properties (from `fetch()` options) are exposed in `Jolokia()` and `Jolokia.request()` calls (with restrictions, because some values/headers may be configured by Jolokia itself)
* no https://en.wikipedia.org/wiki/JSONP[JSONP] support
* `jolokia.request` call based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises[Promises]
** previously, user was passing `success` and `error` options for `jolokia.request()` call and _both_ were used in successful `xhr` call (no transport error for example) - `error` was called for logical errors (when JSON returned from Jolokia contained `error` value and/or status was not `200`)
** both `success` and `error` callbacks passed to `jolokia.request()` were used in single callback passed with https://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings[`ajaxSettings.success`]
** no support for global `ajaxError`. This callback was passed as https://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings[`ajaxSettings.error`]
** now, with https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API[Fetch API], `request()` returns a promise that resolves to whatever is needed:
*** a text response, when `dataType=text`
*** a JSON response (array) by default (when `dataType=json`)
*** `undefined`, when callbacks are specified as it is with existing jolokia.js
*** Fetch API https://developer.mozilla.org/en-US/docs/Web/API/Response[Response object], when user specifies
`resolve="response"` in request options. User may further resolve it to json, text, blob, ...
* Code base is using TypeScript which is processed by https://rollupjs.org/[Rollup.js]
* Because of the way var-args and optional arguments are handled, jolokia-simple.js's `execute` method takes request options before operation arguments

== Developer notes

The goal of client/javascript-esm directory is to provide a _Jolokia monorepo_ based on:

* yarn workspaces to organize interdependent modules
* https://rollupjs.org/[Rollup.js] as a bundler to provide UMD files for browsers and ES modules for browsers and other bundlers (like Webpack).
* Typescript as main langage for source an tests
* https://jestjs.io/[Jest] tests written in Typescript

The challenge is to have as clean configuration (ESLint, Rollup, tsconfig.json, jest.config.ts) as possible and IDE
should allow to work with multiple packages (`jolokia.js`, `@jolokia.js/d3`, ...) without a need to build anything.

We can't use https://www.typescriptlang.org/docs/handbook/project-references.html[Typescript project references],
because these can't be used with `noEmit: true`.

The trick is (though there may be better ones, or this one may be proved bad) with `exports` field of `package.json`:

[,json]
----
{
  "exports": {
    ".": {
      "types": "./dist/dts/jolokia.d.ts",
      "import": "./dist/jolokia.mjs",
      "default": "./src/jolokia.ts"
    }
  }
}
----

It is based on https://nodejs.org/docs/latest/api/packages.html#conditional-exports[Conditional exports] and has these conditions:

* `import` - for users of Jolokia installed with `npm i jolokia.js` after the package is published to NPM registry
* `default` - used when the project was not built yet (so it's used in IDE just after cloning the project)

[]
NOTE:: https://github.com/microsoft/TypeScript/issues/51862[microsoft/TypeScript#51862] mentions `development` conditional, but I'm not sure how/if it's handled at all:
+
[,json]
----
{
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": {
        "development": "./src",
        "default": "./dist/index.mjs"
      },
      "require": {
        "development": "./src",
        "default": "./dist/index.js"
      }
    }
  }
}
----
