////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Artifacts

This page describes available Maven artifacts and shows changes introduced in Jolokia 2.0

=== Jolokia 1.x agent/core (org.jolokia/jolokia-core)

package java.beans
package org.jolokia
package org.jolokia.backend
package org.jolokia.backend.executor
package org.jolokia.backend.plugin
package org.jolokia.config
package org.jolokia.converter
package org.jolokia.converter.json
package org.jolokia.converter.json.simplifier
package org.jolokia.converter.object
package org.jolokia.converter.util
package org.jolokia.detector
package org.jolokia.discovery
package org.jolokia.handler
package org.jolokia.handler.list
package org.jolokia.history
package org.jolokia.http
package org.jolokia.request
package org.jolokia.restrictor
package org.jolokia.restrictor.policy
package org.jolokia.util

=== Jolokia 2.0 server/core (org.jolokia/jolokia-server-core)

org.jolokia.server.core
org.jolokia.server.core.backend
org.jolokia.server.core.config
org.jolokia.server.core.detector
org.jolokia.server.core.http
org.jolokia.server.core.osgi
org.jolokia.server.core.osgi.security
org.jolokia.server.core.osgi.util
org.jolokia.server.core.request
org.jolokia.server.core.request.notification
org.jolokia.server.core.restrictor
org.jolokia.server.core.restrictor.policy
org.jolokia.server.core.service
org.jolokia.server.core.service.api
org.jolokia.server.core.service.impl
org.jolokia.server.core.service.notification
org.jolokia.server.core.service.request
org.jolokia.server.core.service.serializer
org.jolokia.server.core.util
org.jolokia.server.core.util.jmx
