////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Jolokia {jolokia-version}

Jolokia can be
downloaded in two variants: As a binary release including the
agents and the client libraries and the reference manual (PDF
and HTML). The source release contains the complete source
tree mirroring the repository on
https://github.com/jolokia/jolokia[GitHub,role=externalLink].

* *jolokia-{jolokia-version}-bin* (
https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-{jolokia-version}-bin.tar.gz[tar.gz,role=externalLink] |
https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-{jolokia-version}-bin.zip[zip,role=externalLink])
* *jolokia-{jolokia-version}-source* (
https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-{jolokia-version}-source.tar.gz[tar.gz,role=externalLink] |
https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-{jolokia-version}-source.zip[zip,role=externalLink])

The agents and the client library can be downloaded directly
from our maven repository, too:

// TODO: Review artifactIds after 2.0
[%header,cols=2*,role=bodyTable]
|===
|Artifact
|Download

|WAR-Agent
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/{jolokia-version}/jolokia-war-{jolokia-version}.war[jolokia-war-{jolokia-version}.war,role=externalLink]

|WAR-Agent (unsecured)
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war-unsecured/{jolokia-version}/jolokia-war-unsecured-{jolokia-version}.war[jolokia-war-unsecured-{jolokia-version}.war,role=externalLink]

|Osgi-Agent
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-osgi/{jolokia-version}/jolokia-osgi-{jolokia-version}.war[jolokia-osgi-{jolokia-version}.war,role=externalLink]

|Osgi-Agent (full bundle)
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-osgi-bundle/{jolokia-version}/jolokia-osgi-bundle-{jolokia-version}.war[jolokia-osgi-bundle-{jolokia-version}.war,role=externalLink]

|JVM-Agent
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{jolokia-version}/jolokia-jvm-{jolokia-version}.war[jolokia-jvm-{jolokia-version}.war,role=externalLink]

|Java Client Library
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-client-java/{jolokia-version}/jolokia-client-java-{jolokia-version}.war[jolokia-client-java-{jolokia-version}.war,role=externalLink]

|Jolokia JSR-160 JMX Adapter
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jmx-adapter/{jolokia-version}/jolokia-jmx-adapter-{jolokia-version}.war[jolokia-jmx-adapter-{jolokia-version}.war,role=externalLink]

|Jolokia JSR-160 JMX Adapter Kubernetes Extension
|https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-kubernetes/{jolokia-version}/jolokia-kubernetes-{jolokia-version}.war[jolokia-kubernetes-{jolokia-version}.war,role=externalLink]
|===

=== JavaScript Library

The Jolokia JavaScript client library comes in two variants:
`jolokia.js` contains the basics and can be used
with its `request()` for sending JSON
requests. `jolokia-simple.js` adds on this code
and provides a simplified API for Jolokia request, but is
slightly less powerful. Finally,
`jolokia-cubism.js` contains the Jolokia
https://square.github.com/cubism/[Cubism,role=externalLink] integration which adds Jolokia as a data
source. The `-min` versions are
compressed with all documentation stripped off and
recommended for production use.

[%header,cols=2*,role=bodyTable]
|===
|Script
|Download

|Base script
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia.js[jolokia.js,role=externalLink]

|Base script, compressed
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-min.js[jolokia-min.js,role=externalLink]

|Simplified API
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-simple.js[jolokia-simple.js,role=externalLink]

|Simplified API, compressed
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-simple-min.js[jolokia-simple-min.js,role=externalLink]

|Jolokia Cubism Integration
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-cubism.js[jolokia-cubism.js,role=externalLink]

|Jolokia Cubism Integration, compressed
|https://github.com/jolokia/jolokia/releases/download/v{jolokia-version}/jolokia-cubism-min.js[jolokia-cubism-min.js,role=externalLink]
|===

=== Maven

The main agent functionality is encapsulated in a core jar,
which can be easily used in own projects. Also, the Java
client library can be used as a Maven dependency. The dependencies are

[source,xml,subs="attributes,verbatim"]
----
<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-server-core</artifactId>
    <version>{jolokia-version}</version>
</dependency>
----

and
[source,xml,subs="attributes,verbatim"]
----
<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-client-java</artifactId>
    <version>{jolokia-version}</version>
</dependency>
----

// TODO: check what is javascript-maven-plugin
The JavaScript library can easily be used as Maven
dependency by use of `javascript-maven-plugin`:

[source,xml,subs="attributes,verbatim"]
----
<dependency>
    <groupId>org.jolokia</groupId>
    <artifactId>jolokia-client-javascript</artifactId>
    <type>javascript</type>
    <version>{jolokia-version}</version>
</dependency>
----

Use a classifier `compressed` for referencing to
the compressed versions. A full example, including the
plugin configuration can be found in the
link:../reference/html/clients.html#js-maven[Reference Manual]

The released Jolokia artifacts as well as SNAPSHOTS are available from
https://search.maven.org/[Maven Central,role=externalLink].
