////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
// :doctype: book
// :reproducible:
// :noheader:
// :nofooter:
// :description: Jolokia is an alternative to JSR-160 connectors for remote JMX access. It provides REST-like access to JMX with JSON over HTTP.
// :source-highlighter: rouge

++++
<div class="teaser">
    <strong>Jolokia</strong> is remote JMX with JSON over HTTP.<br />
    <div class="subtitle">
    It is fast, simple, polyglot and has unique features. It's JMX on <a class="externalLink" href="https://en.wikipedia.org/wiki/Capsaicin">Capsaicin</a>.
    </div>
</div>
++++

Jolokia is a JMX-HTTP bridge giving an alternative to JSR-160 connectors. It is an agent based approach with support for many platforms. In addition to basic JMX operations it enhances JMX remoting with unique features like bulk requests and fine grained security policies.

// A warning about incorrect section nesting, but it's by design...
=== Starting points

* Overview of link:features.html[features] which make Jolokia unique for JMX remoting.
* The link:documentation.html[documentation] includes a link:tutorial.html[tutorial] and a https://jolokia.org/reference/html/index.html[reference manual].
* link:agent.html[Agents] exist for many platforms (Java EE, OSGi, JVM).
* link:support.html[Support] is available through various channels.
* link:support.html#Source[Contributions] are highly appreciated, too.

include::news.adoc[]
