////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
// currentStableVersion is defined in POM
:currentStableVersion:

== Migration

_draft_

* Switch from `javax.servlet` to `jakarta.servlet` (JavaEE/JakartaEE 8 → JakartaEE 9+)
* `jolokia:type=Config` MBean is now registered with `agent=agentId` ObjectName property.
* `roo-addon` is no longer available
* OSGi code registers `org.jolokia.server.core.osgi.OsgiAgentServlet` using Whiteboard Specification instead of Http Service specification
* `listenForHttpService` option is replaced (with deprecation) with `registerWhiteboardServlet` option