////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Migration

_draft_

* Switch from `javax.servlet` to `jakarta.servlet` (JavaEE/JakartaEE 8 → JakartaEE 9+)
* `jolokia:type=Config` MBean is now registered with `agent=agentId` ObjectName property.
* `roo-addon` is no longer available
* OSGi code registers `org.jolokia.server.core.osgi.OsgiAgentServlet` using Whiteboard Specification instead of Http Service specification
* `listenForHttpService` option is replaced (with deprecation) with `registerWhiteboardServlet` option
* list artifact IDs and their usage
* https://github.com/jolokia/jolokia/issues/612 about request dispatchers/handlers
* no more jolokia-spring-plugin.jar, because `/META-INF/spring/*.xml` was handled by Spring-DM.
* 3 jars are required now at least (service-jmx and service-serializer in addition to server-core)
* classifier for standalone agent changed in 1.7.0 from `agent` to empty, but it messed up with transitive dependencies. Because the artifact id itself changed from `jolokia-jvm` to `jolokia-agent-jvm`, we've decided to add `standalone` classifier to not have a jar like `jolokia-agent-jvm-2.0.0-agent.jar`.

=== JavaScript Client

* The minimum supported JavaScript version is now ES5. For environments with ES3 and older JavaScript versions, keep using old versions of the JavaScript client provided with Jolokia 1.x.
* Since it is based on ES5, `JSON2.js` is no longer required.
* Now it also supports installation with NPM or Yarn. You can install it with `npm i jolokia.js` or `yarn add jolokia.js`.
* You can also use it with a TypeScript project, as the client provides its type definitions with the package.
