////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
== News

=== Jolokia has a new home!

[.news-date]
2023-12-01

After years of preparation, reviewing, restructuring, refactoring and polishing, Jolokia 2.0 is released and available in https://repo.maven.apache.org/maven2/org/jolokia/[Maven Central].

[.news-date]
2023-07-13

Yes, finally we moved Jolokia from my (rhuss) personal
account to a dedicated GitHub organisation:
https://github.com/jolokia[https://github.com/jolokia,role=externalLink].
I'm super happy that the story of Jolokia continues and you
will see quite some new faces very soon. Thanks Tadayoshi,
Grzegorz, Aurélien and all the other fine folks from Red Hat
who started to revive Jolokia. Also, Jolokia 2.0 becomes a realistic
option again. Stay tuned!

link:news-older.html[Older news ...]
