////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

// TODO: this script was added, but it refers to nonexisting http://api.flattr.com/js/0.5.0/load.js
// <script type="text/javascript" src="js/flattr.js"></script>

== Support

There a multiple channels from where support for Jolokia can be
obtained. Bugs are tracked via
https://github.com/rhuss/jolokia/issues[GitHub,role=externalLink],
questions should be preferably posed in the Jolokia
link:forum.html[Forum].

On the other hand, the are ways for supporting the development
of Jolokia, too. You can contribute code and bug-fixes via
https://github.com/rhuss/jolokia[GitHub,role=externalLink] (prefered)
or with financial support (donations via Pledgie or flattring
Jolokia).

=== Communication channels

Forum::
There's a link:forum.html[forum] for Jolokia
related discussions. Don't hesitate to fill it up with
your questions and suggestions.

IRC::
Feel free to join us on
https://freenode.net[Freenode,role=externalLink], and discuss on
**`#jolokia`** about JMX and the
link:irc.html[web chat]
for a quick contact.

Bug Reports and Feature Requests::
Jolokia uses GitHub for
https://github.com/rhuss/jolokia/issues[bug tracking,role=externalLink]
and release management. Please fill in any
issue you find or feature requests you have.

[#Source]
=== Source

Jolokia uses
https://github.com/rhuss/jolokia[GitHub,role=externalLink] as source
repository and employs a
https://help.github.com/pull-requests/[Fork + Pull Model,role=externalLink]
for development. The git clone URL is `git@github.com:rhuss/jolokia.git`.

We are always looking for volunteers to enhance Jolokia. If
you would like start to participate, we suggest the
following way:

* Check for an open feature request
you like or open bug at
https://github.com/rhuss/jolokia/issues[GitHub,role=externalLink].
* Fork Jolokia by visiting the
https://github.com/rhuss/jolokia[project page,role=externalLink]
(use "Fork" from the menu).
* Your contribution must be donated under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache Public License,role=externalLink] and you
should sign-off your commits that you conform to the https://developercertificate.org/[Developer Certificate of Origin,role=externalLink]
(i.e. that you have written the code on your own). To do so, add a line `Signed-off-by: Your Name
<your.name@example.com>` to your commit message. (`git -s` will do this for you).
Only real names are allowed here.
* After finishing your implementation, send a
https://help.github.com/pull-requests[pull request,role=externalLink].
* After briefly reviewing the code contribution, it will
integrated into the master repository.

Please note, that all the contributed code must be
licensed under link:license.html[Apache License] Version 2 and you must sign-off the contribution (see above).

=== T-Shirts

If you like the software and want to spread the word, we have some quite some cool T-Shirts,
Baseball Caps, Coffee Mugs, ... over there in our
https://jolokia.spreadshirt.de[merchandising shop,role=externalLink].

=== Your Support for Jolokia

++++
<div style="float:right; margin-right: 50px; margin-top: 20px;">
    <a class="FlattrButton" style="display:none;" href="https://www.jolokia.org"></a>
</div>
++++

Jolokia is free software, released under the business friendly
Apache License. That's mostly because I believe that open
source software is the real driving force behind software
innovation and I highly appreciate the fine pieces of open
source software engineering I had the luck to use in my daily
work. I love this.

Nevertheless, if you want to support the development of
Jolokia (it is still a hobby project) and you like this
software you can https://www.flattr.com[flattr,role=externalLink] it.
