////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
[#tools-roo]
== Jolokia Roo Addon

The Jolokia https://www.springsource.org/roo[Roo] addon allows for easy
integration of an agent servlet in an existing Roo web
project.

[NOTE]
====
This addon has been submitted to the Roobot, a central Roo addon
registry. Until it is publicly available you can directly
install the addon from our repository.

----
roo> osgi obr url add --url http://labs.consol.de/maven/repository/roo-repository.xml
roo> osgi obr start --bundleSymbolicName org.jolokia.roo
----

Alternatively, if there are problems with the approach above
(which is currently the case because the hard coded public PGP
keyserver which is used by Roo 1.1.1 is down) and you don't need
PGP verification, you can install the addon bundle directly from
our repository:

----
roo> osgi start --url http://labs.consol.de/maven/repository/org/jolokia/jolokia-roo/0.83/jolokia-roo-0.83.jar
----
====

As soon as `src/main/webapp/WEB-INF/web.xml`
is available in the roo project, Jolokia can be setup with the
command `jolokia setup`. This will add the
proper dependency in the `pom.xml` and adapt
`web.xml` so that an agent servlet gets
registered under the subcontext `jolokia` (so,
when you web application is deployed under the context
`/mywebapp`, the agent is reachable under
`/mywebapp/jolokia`. This command knows about
the options described in <<table-roo-options>>,
all of which are optional.

[#table-roo-options]
.Jolokia setup Options
|===
|Option|Description

|`--addPolicy`
|This adds an additional
`jolokia-access.xml` below
`src/main/resources` to allow putting
access restrictions into place. The installed template,
however, doesn't come with any restriction but contains
sample configurations commented out.

|`--addJsr160Proxy`
|Adapts the agent servlet's `init-param`
to add an additional
`org.jolokia.service.jsr160.Jsr160RequestHandler`
request dispatcher which allows the installed servlet to act
as an JSR-160 proxy. See <<proxy>> for details
about the JSR-160 proxy

|`--addDefaultInitParams`
|By default, the servlet gets registered without any init
parameters. With this option, all available
`init-param` are added to the servlet
definition with their default values.
|===
