////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Jolokia Java Client library

The Jolokia Java client bindings provide typeless access to a
remote JMX `MBeanServer`. Its programming model follows a
request-response paradigm and is easy to use:

[source,java,options=nowrap]
----
JolokiaClient jolokiaClient = new JolokiaClientBuilder().url("http://localhost:8080/jolokia")
        .user("jolokia")
        .password("jolokia")
        .build();
JolokiaReadRequest req = new JolokiaReadRequest("java.lang:type=Memory", "HeapMemoryUsage");
req.setPath("used");
JolokiaReadResponse resp = jolokiaClient.execute(req);
System.out.println("Memory used: " + resp.getValue());
----

This client library is described in detail with all
configuration options in the
link:../reference/html/manual/clients.html#client-java[reference manual].

The documentation chapter provide much more information about how to configure the Jolokia Client and how
to choose the implementation of HTTP Client library.

Jolokia can use 3 implementations of the HTTP Client:

* https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpClient.html[JDK HTTP Client,role=externalLink,window=_blank]
* https://hc.apache.org/httpcomponents-client-4.5.x/index.html[Apache HttpClient 4,role=externalLink,window=_blank]
* https://hc.apache.org/httpcomponents-client-5.5.x/index.html[Apache HttpClient 5,role=externalLink,window=_blank]
