////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////

== Jmx4Perl

As described in this link:../about.html[story], Jolokia has its origins
in the Perl world where it starts as a simple solution for monitoring
Java EE applications with
https://www.nagios.org[Nagios]. https://www.jmx4perl.org[Jmx4perl]
was its former name, which in addition to the agents contains
powerfule Perl modules for accessing Jolokia instrumented
servers. These modules are the foundation for tools like
`check_jmx4perl`, a Nagios plugin with a rich feature set,
`jmx4perl`, a command line utility for accessing the agents and
`j4psh`, a readline based remote JMX shell.

Jmx4perl requests looks like

[source,bash]
----
use strict;
use JMX::Jmx4Perl;
use JMX::Jmx4Perl::Alias;   # Import MBean aliases

# Basic usage
print "Memory Used: ",
      JMX::Jmx4Perl
          ->new(url => "http://localhost:8080/jolokia",
                user => "jolokia",
                password => "jolokia")
          ->get_attribute(MEMORY_HEAP_USED), "\n";

# Advanced:
my $jmx = new JMX::Jmx4Perl(url => "http://localhost:8080/jolokia",
                            user => "jolokia",
                            password => "jolokia",
                            product => "tomcat");
my $request = new JMX::Jmx4Perl::Request({type => "read",
                                         mbean => "java.lang:type=Memory",
                                         attribute => "HeapMemoryUsage",
                                         path => "used"});
my $response = $jmx->request($request);
print "Memory used: ",$response->value(),"\n";
----

More information about jmx4perl can be found on its
https://metacpan.org/dist/jmx4perl[CPAN page].
