////
  Copyright 2009-2023 Roland Huss

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
////
[#read]
=== Reading attributes (read)

Reading MBean attributes is probably the most used JMX method,
especially when it comes to monitoring. Concerning Jolokia, it is
also the most powerful one with the richest semantics. Obviously
the value of a single attribute can be fetched, but Jolokia
supports also fetching of a list of given attributes on a single
MBean or even on multiple MBeans matching a certain pattern.

Reading attributes are supported by both kinds of requests,
`GET` and `POST`.

NOTE: Don't confuse fetching multiple attributes on possibly multiple
MBeans with bulk requests. A single read request will always
result in a single read response, even when multiple attribute
values are fetched. Only the single response's structure of the
`value` will differ depending on what kind of
read request was performed.

A read request for multiple attributes on the same MBean is
initiated by giving a list of attributes to the request. For a
POST request this is an JSON array, for a GET request it is a
comma separated list of attribute names (where slashes and
exclamation marks must be escaped as described in
<<escape-rules>>). If no attribute is provided, then all
attributes are fetched.  The MBean name can be given as a pattern
in which case the attributes are read on all matching MBeans. If a
MBean pattern and multiple attributes are requested, then only the
value of attributes which matches both are returned, the others
are ignored.

Paths can be used with pattern and multiple attribute read as well. In order to
skip the extra value levels introduced by a pattern read, the wildcard
`\*` can be used. For example, a read request for the MBean Pattern
`pass:[java.lang:type=GarbageCollector,*]` for the Attribute `LastGcInfo`
returns a complex structure holding information about the last garbage collection. If one is
interested only for the duration of the garbage collection, a path `used` could be used if
this request wouldn't be a pattern request (i.e. refers a specific, single MBean). But in this case since a
nested map with MBean and Attribute names is returned, the path `pass:[*/*/used]` has to be used
in order to skip the two extra levels for applying the path. The two levels are returned nevertheless, though.
Note that in the following example the final value is _not_ the full GC-Info but only the
value of its `used` entry:

[,json]
----
"value": {
  "java.lang:name=PS MarkSweep,type=GarbageCollector": {
    "LastGcInfo": null
  },
  "java.lang:name=PS Scavenge,type=GarbageCollector": {
    "LastGcInfo": 7
  }
}
----

The following rule of thumb applies:

* If a wildcard is used, everything at that point in the path is
matched. The next path parts are used to match from there
on. All the values on this level are included.
* Every other path part is literally compared against the values
on that level. If there is a match, this value is
_removed_ in the answer so that at the end
you get back a structure with the values on the wildcard levels
and the leaves of the matched parts.
* If used with wildcards, paths behave also like
filters. E.g. you can use a path `pass:[*/*/used]` on
the MBean pattern `java.lang:*` and get back
only that portions which contains "used" as key, all others are
ignored.

[#get-read]
==== GET read request

The GET URL for a read request has the following format:

----
<base-url>/read/<mbean name>/<attribute name>/<inner path>
----

.GET Read Request
|===
|Part|Description|Example

|`<mbean name>`
|The
https://download.oracle.com/javase/6/docs/api/javax/management/ObjectName.html[ObjectName]
of the MBean for which the attribute should be fetched. It
contains two parts: A domain part and a list of properties
which are separated by `:`. Properties
themselves are combined in a comma separated list of
key-value pairs. This name can be a pattern in which case
multiple MBeans are queried for the attribute value.
|`java.lang:type=Memory`

|`<attribute name>`
|Name of attribute to read. This can be a list of Attribute
names separated by comma. Slashes and exclamations marks need
to be escaped as described in <xref
<<escape-rules>>. If no attribute is given, all
attributes are read.
|`HeapMemoryUsage`

|`<inner path>`
|This optional part describes an _inner
path_ as described in <<paths>>
|`used`
|===

With this URL the used heap memory can be obtained:
----
http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/used
----

[#post-read]
==== POST read request

A the keys available for read POST requests are shown in the
following table.

.POST Read Request
|===
|Key|Description|Example

<tr>
|`type`
|*`read`*
|

|`mbean`
|MBean's ObjectName which can be a pattern
|`java.lang:type=Memory`

|`attribute`
|Attribute name to read or a JSON array containing a list
of attributes to read. No attribute is given, then all attributes
are read.
|`HeapMemoryUsage`, `[ "HeapMemoryUsage", "NonHeapMemoryUsage" ]`

|`path`
|Inner path for accessing the value of a complex value
(<<paths>>)
|`used`
|===

The following request fetches the number of active threads:
[,json]
----
{
  "type": "read",
  "mbean": "java.lang:type=Threading",
  "attribute": "ThreadCount"
}
----

[#response-read]
==== Read response

The general format of the JSON response is described in
<<responses>> in detail.  A typical response for an
attribute read operation for an URL like

----
http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/
----

[,json]
----
{
  "value": {
    "init": 134217728,
    "max": 532742144,
    "committed": 133365760,
    "used": 19046472
  },
  "status": 200,
  "timestamp": 1244839118,
  "request": {
    "mbean": "java.lang:type=Memory",
    "type": "read",
    "attribute": "HeapMemoryUsage"
  },
  "history": [
    {
      "value": {
        "init": 134217728,
        "max": 532742144,
        "committed": 133365760,
        "used": 18958208
      },
      "timestamp": 1244839045
    },
    ....
  ]
}
----
The `value` contains the response's
value. For simple data types it is a scalar value, more complex
types are serialized into a JSON object. See
<<serialization>> for detail on object serialization.

For a read request to a single MBean with multiple attributes, the
returned value is a JSON object with the attribute names as keys
and their values as values. For example a request to
`http://localhost:8080/jolokia/read/java.lang:type=Memory`
leads to

[,json]
----
{
  "timestamp": 1317151518,
  "status": 200,
  "request": {
    "mbean": "java.lang:type=Memory",
    "type": "read"
  },
  "value": {
    "Verbose": false,
    "ObjectPendingFinalizationCount": 0,
    "NonHeapMemoryUsage": {
      "max": 136314880, "committed": 26771456, "init": 24317952, "used": 15211720
    },
    "HeapMemoryUsage": {
      "max": 129957888, "committed": 129957888, "init": 0, "used": 2880008
    }
  }
}
----

A request to a MBean pattern returns as value a JSON object,
with the MBean names as keys and as value another JSON object
with the attribute name as keys and the attribute values as
values. For example a request
`http://localhost:8080/jolokia/read/java.lang:type=*/HeapMemoryUsage`
returns something like

[,json]
----
{
  "timestamp": 1317151980,
  "status": 200,
  "request": {
    "mbean": "java.lang:type=*",
    "attribute": "HeapMemoryUsage",
    "type": "read"
  },
  "value": {
    "java.lang:type=Memory": {
      "HeapMemoryUsage": {
        "max": 129957888, "committed": 129957888, "init": 0, "used": 3080912
      }
    }
  }
}
----
