name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java: [8, 11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build
      run: mvn --no-transfer-progress -B clean verify
